services:

  postgres:
    image: 'postgres:17.2-alpine'
    environment:
      - 'POSTGRES_DB=sample'
      - 'POSTGRES_PASSWORD=1234'
      - 'POSTGRES_USER=sample'
    ports:
      - '54320:5432'
    volumes:
      - postgres_data_0:/var/lib/postgresql/data

  redis:
    image: 'redis:7.4-alpine'
    ports:
      - "63790:6379"
    volumes:
      - redis_data_0:/data

volumes:
  postgres_data_0:
  redis_data_0: